### PR TITLE
Git tags to specify what version of the notebook and ipywidgets that Thebe depends on.

### PR DESCRIPTION
**Pull request by jdfreder**
Alternatively, we may be able to use a Javascript package manager and another CDN.

This PR just updates the README, but HEAD will need to be tagged as `notebook3.x`.

### CODE REVIEW

**Comment by jdfreder** [comment]
@zischwartz @rgbkrk @fchasen

**Comment by rgbkrk** [comment]
We have a CDN Jon, at cdn.jupyter.org!

I'd be happy with putting thebe at:

```
https://cdn.jupyter.org/thebe/{versioned_path}
```

**Comment by jdfreder** [comment]
^ ah, that was what I thought at first : https://github.com/jupyter/cdn.jupyter.org/issues/1

**Comment by jdfreder** [comment]
Updated to use our CDN

**Comment by rgbkrk** [comment]
> Updated to use our CDN [but not the first one yet]

**Comment by jdfreder** [comment]
Sorry, should have mentioned, this depends on #58

**Pull request merged**
